; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = esp32s3_16mb ; Change this to whatever you are actively testing

; ----------------------------------------------------------------
; SHARED SETTINGS (Applies to all boards and sizes)
; ----------------------------------------------------------------
[env]
platform = espressif32@6.5.0
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps = 
    bblanchon/ArduinoJson @ 7.0.4
    makuna/NeoPixelBus @ 2.8.4
    links2004/WebSockets @ 2.7.2
    knolleary/PubSubClient @ 2.8
    sapteinkabeltann/Lua 5.1 for ESP32 @ 5.1.5
    esphome/ESPAsyncWebServer-esphome@3.1.0
lib_ignore = 
    WiFi101

; ================================================================
; ESP32 CLASSIC (Xtensa LX6)
; ================================================================

[env:esp32_4mb]
board = esp32dev
build_flags = -D CORE_DEBUG_LEVEL=0
board_upload.flash_size = 4MB
board_build.partitions = partitions_4MB.csv

[env:esp32_8mb]
board = esp32dev
build_flags = -D CORE_DEBUG_LEVEL=0
board_upload.flash_size = 8MB
board_build.partitions = partitions_8MB.csv

[env:esp32_16mb]
board = esp32dev
build_flags = -D CORE_DEBUG_LEVEL=0
board_upload.flash_size = 16MB
board_build.partitions = partitions_16MB.csv

[env:esp32_32mb]
board = esp32dev
build_flags = -D CORE_DEBUG_LEVEL=0
board_upload.flash_size = 32MB
board_build.partitions = partitions_32MB.csv


; ================================================================
; ESP32-S3 (Xtensa LX7 + PSRAM Support)
; ================================================================

[env:esp32s3_4mb]
board = esp32-s3-devkitc-1
board_upload.flash_size = 4MB
board_build.partitions = partitions_4MB.csv
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 

[env:esp32s3_8mb]
board = esp32-s3-devkitc-1
board_upload.flash_size = 8MB
board_build.partitions = partitions_8MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 

[env:esp32s3_16mb]
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_build.partitions = partitions_16MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 

[env:esp32s3_32mb]
board = esp32-s3-devkitc-1
board_upload.flash_size = 32MB
board_build.partitions = partitions_32MB.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1